name = "ExampleProject"
uuid = "e64637de-a8fd-4a3d-b020-461d18565bf0"
authors = ["Matthew Schlegel <mkschleg@gmail.com>"]
version = "0.1.0"

[deps]
ChoosyDataLoggers = "edd8e46e-3ca5-477d-bc67-b483295d3b14"
